"""add workflow tables

Revision ID: 1319a2c257ce
Revises: 69a2d4f59e45
Create Date: 2026-05-13 22:47:04.540232

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1319a2c257ce'
down_revision: Union[str, None] = '69a2d4f59e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_key', sa.String(length=100), nullable=False),
    sa.Column('workflow_label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflows_workflow_key'), 'approval_workflows', ['workflow_key'], unique=True)
    op.create_table('approval_workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_label', sa.String(length=200), nullable=False),
    sa.Column('approver_type', sa.String(length=50), nullable=False),
    sa.Column('approver_role_id', sa.Integer(), nullable=True),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_level', sa.Integer(), nullable=True),
    sa.Column('pending_status', sa.String(length=100), nullable=True),
    sa.Column('approved_status', sa.String(length=100), nullable=True),
    sa.Column('can_skip', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approver_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_workflow_steps_id'), 'approval_workflow_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_workflow_steps_id'), table_name='approval_workflow_steps')
    op.drop_table('approval_workflow_steps')
    op.drop_index(op.f('ix_approval_workflows_workflow_key'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_table('approval_workflows')
    # ### end Alembic commands ###
